export RABBITMQ_HOST="127.0.0.1"
export RABBITMQ_PORT="5672"
export RABBITMQ_QUEUE="hello"
export MYSQL_HOST="127.0.0.1"
export MYSQL_USER="root"
export MYSQL_PASSWORD="rd2021"
export MYSQL_DB="hello"
